version: "3.9"

services:
  hub-db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME:-hub}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./db/postgres-data:/var/lib/postgresql/data
    networks:
      - hub-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 10

  hub-api:
    build: .
    environment:
      HOST: ${HOST:-api.verbohub.com.br}
      DB_USER: ${DB_USER:-postgres}
      DB_HOST: ${DB_HOST:-hub-db}
      DB_NAME: ${DB_NAME:-hub}
      DB_PASSWORD: ${DB_PASSWORD:-password}
      DB_PORT: ${DB_PORT:-5432}
      DATABASE_URL: "postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}"
      PORT: ${PORT:-3000}
    ports:
      - "3000:3000"
    depends_on:
      hub-db:
        condition: service_healthy
    networks:
      - hub-net
    env_file:
      - .env

networks:
  hub-net:
    name: hub-net
