name: Branching

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  push:
    paths:
      - '**/*.test.ts'
      - '.github/**'
      - '.eb*'

jobs:
  pull-request-branching:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2  # Ensure enough history is fetched

      - name: PR Branching
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_OWNER }}
        run: |
          PR_NUMBER=$(jq --raw-output .number "$GITHUB_EVENT_PATH")
          BRANCH_NAME=$(jq --raw-output .pull_request.head.ref "$GITHUB_EVENT_PATH")

          if [[ "$BRANCH_NAME" == feature/* ]]; then
            curl -s -H "Authorization: token $GITHUB_TOKEN" \
              -H "Content-Type: application/json" \
              -X POST \
              -d '{"labels":["api","enhancement"]}' \
              "https://api.github.com/repos/${{ github.repository }}/issues/$PR_NUMBER"
          elif [[ "$BRANCH_NAME" == hotfix/* ]]; then
            curl -s -H "Authorization: token $GITHUB_TOKEN" \
              -H "Content-Type: application/json" \
              -X POST \
              -d '{"labels":["api","bug"]}' \
              "https://api.github.com/repos/${{ github.repository }}/issues/$PR_NUMBER"
          fi

  test-branching:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2  # Ensure enough history is fetched

      - name: Test Branching
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_OWNER }}
        run: |
          PR_NUMBER=$(jq --raw-output .number "$GITHUB_EVENT_PATH")
          for file in $(git diff --name-only HEAD~1 HEAD); do
            if [[ "$file" == *.test.ts ]]; then
              curl -s -H "Authorization: token $GITHUB_TOKEN" \
                -H "Content-Type: application/json" \
                -X POST \
                -d '{"labels":["api","unit-test"]}' \
                "https://api.github.com/repos/${{ github.repository }}/issues/$PR_NUMBER"
            fi
          done

  devops-branching:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2  # Ensure enough history is fetched

      - name: DevOps Branching
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_OWNER }}
        run: |
          PR_NUMBER=$(jq --raw-output .number "$GITHUB_EVENT_PATH")
          for file in $(git diff --name-only HEAD~1 HEAD); do
            if [[ "$file" == .github/* || "$file" == .eb* ]]; then
              curl -s -H "Authorization: token $GITHUB_TOKEN" \
                -H "Content-Type: application/json" \
                -X POST \
                -d '{"labels":["devops"]}' \
                "https://api.github.com/repos/${{ github.repository }}/issues/$PR_NUMBER"

              # Remove 'api' label if 'devops' label is added
              curl -s -H "Authorization: token $GITHUB_TOKEN" \
                -H "Content-Type: application/json" \
                -X POST \
                -d '{"labels":["devops"], "remove":["api"]}' \
                "https://api.github.com/repos/${{ github.repository }}/issues/$PR_NUMBER"
            fi
          done
