name: Branching

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  pull-request-branching:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: PR Branching
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_OWNER }}
        run: |
          PR_NUMBER=$(jq --raw-output .number "$GITHUB_EVENT_PATH")
          BRANCH_NAME=$(jq --raw-output .pull_request.head.ref "$GITHUB_EVENT_PATH")

          if [[ "$BRANCH_NAME" == feature/* ]]; then
            curl -s -H "Authorization: token $GITHUB_TOKEN" \
              -H "Content-Type: application/json" \
              -X POST \
              -d '{"labels":["api","enhancement"]}' \
              "https://api.github.com/repos/${{ github.repository }}/issues/$PR_NUMBER/labels"
          elif [[ "$BRANCH_NAME" == hotfix/* ]]; then
            curl -s -H "Authorization: token $GITHUB_TOKEN" \
              -H "Content-Type: application/json" \
              -X POST \
              -d '{"labels":["api","bug"]}' \
              "https://api.github.com/repos/${{ github.repository }}/issues/$PR_NUMBER/labels"
          fi

  test-branching:
    runs-on: ubuntu-latest
    needs: pull-request-branching
    continue-on-error: true
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Test Branching
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_OWNER }}
        run: |
          PR_NUMBER=$(jq --raw-output .number "$GITHUB_EVENT_PATH")
          TEST_FILE_CHANGED=false
          for file in $(git diff --name-only HEAD~1 HEAD); do
            if [[ "$file" == *.test.ts ]]; then
              TEST_FILE_CHANGED=true
              break
            fi
          done

          if [ "$TEST_FILE_CHANGED" = true ]; then
            curl -s -H "Authorization: token $GITHUB_TOKEN" \
              -H "Content-Type: application/json" \
              -X POST \
              -d '{"labels":["api","unit-test"]}' \
              "https://api.github.com/repos/${{ github.repository }}/issues/$PR_NUMBER/labels"
          fi

  devops-branching:
    runs-on: ubuntu-latest
    needs: test-branching
    continue-on-error: true
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: DevOps Branching
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_OWNER }}
        run: |
          PR_NUMBER=$(jq --raw-output .number "$GITHUB_EVENT_PATH")
          DEVOPS_FILE_CHANGED=false
          for file in $(git diff --name-only HEAD~1 HEAD); do
            if [[ "$file" == .github/* || "$file" == .eb* ]]; then
              DEVOPS_FILE_CHANGED=true
              break
            fi
          done

          if [ "$DEVOPS_FILE_CHANGED" = true ]; then
            # Add devops label
            curl -s -H "Authorization: token $GITHUB_TOKEN" \
              -H "Content-Type: application/json" \
              -X POST \
              -d '{"labels":["devops"]}' \
              "https://api.github.com/repos/${{ github.repository }}/issues/$PR_NUMBER/labels"

            # Get current labels
            CURRENT_LABELS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
              "https://api.github.com/repos/${{ github.repository }}/issues/$PR_NUMBER" | jq -r '[.labels | .[].name] | join(",")')

            # Remove 'api' label if 'devops' label is added
            if [[ "$CURRENT_LABELS" == *"api"* ]]; then
              UPDATED_LABELS=$(echo $CURRENT_LABELS | sed 's/api,//g' | sed 's/,api//g')

              curl -s -H "Authorization: token $GITHUB_TOKEN" \
                -H "Content-Type: application/json" \
                -X PATCH \
                -d "{\"labels\":[\"$(echo $UPDATED_LABELS | sed 's/,/\",\"/g')\"]}" \
                "https://api.github.com/repos/${{ github.repository }}/issues/$PR_NUMBER"
            fi
          fi
