name: Branch Labeler

on:
  pull_request:
    branches:
      - 'feature/*'
      - 'hotfix/*'
  push:
    paths:
      - '*test.ts'
      - '.github/**'
      - '.eb*'

jobs:
  label-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Label feature branches
        if: startsWith(github.ref, 'refs/heads/feature/')
        run: |
          curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Content-Type: application/json" \
          -X POST \
          -d '{"labels":["api","enhancement"]}' \
          "https://api.github.com/repos/${{ github.repository }}/issues/$(echo ${{ github.ref }} | cut -d '/' -f 3)"

      - name: Label hotfix branches
        if: startsWith(github.ref, 'refs/heads/hotfix/')
        run: |
          curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Content-Type: application/json" \
          -X POST \
          -d '{"labels":["api","bug"]}' \
          "https://api.github.com/repos/${{ github.repository }}/issues/$(echo ${{ github.ref }} | cut -d '/' -f 3)"

  label-test-files:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Label test file changes
        run: |
          for file in $(git diff --name-only ${{ github.event.before }} ${{ github.sha }}); do
            if [[ "$file" == *"test.ts"* ]]; then
              curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Content-Type: application/json" \
              -X POST \
              -d '{"labels":["api","test"]}' \
              "https://api.github.com/repos/${{ github.repository }}/issues/$(echo ${{ github.ref }} | cut -d '/' -f 3)"
            fi
          done

  label-devops-files:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Label devops file changes
        run: |
          for file in $(git diff --name-only ${{ github.event.before }} ${{ github.sha }}); do
            if [[ "$file" == .github/* || "$file" == .eb* ]]; then
              curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Content-Type: application/json" \
              -X POST \
              -d '{"labels":["devops"]}' \
              "https://api.github.com/repos/${{ github.repository }}/issues/$(echo ${{ github.ref }} | cut -d '/' -f 3)"
            fi
          done
