name: Branch Labeler

on:
  create:

  push:
    paths:
      - '**/test.ts'
      - '.github/**'
      - '.eb*'
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  label-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Label pull requests
        run: |
          PR_NUMBER=$(jq --raw-output .number "$GITHUB_EVENT_PATH")
          BRANCH_NAME=$(jq --raw-output .pull_request.head.ref "$GITHUB_EVENT_PATH")

          if [[ "$BRANCH_NAME" == feature/* ]]; then
            curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Content-Type: application/json" \
              -X POST \
              -d '{"labels":["api","enhancement"]}' \
              "https://api.github.com/repos/${{ github.repository }}/issues/$PR_NUMBER"
          elif [[ "$BRANCH_NAME" == hotfix/* ]]; then
            curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Content-Type: application/json" \
              -X POST \
              -d '{"labels":["api","bug"]}' \
              "https://api.github.com/repos/${{ github.repository }}/issues/$PR_NUMBER"
          fi

  label-test-files:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Label test file changes
        run: |
          for file in $(git diff --name-only ${{ github.event.before }} ${{ github.sha }}); do
            if [[ "$file" == *"test.ts"* ]]; then
              PR_NUMBER=$(jq --raw-output .number "$GITHUB_EVENT_PATH")
              curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                -H "Content-Type: application/json" \
                -X POST \
                -d '{"labels":["api","unit-test"]}' \
                "https://api.github.com/repos/${{ github.repository }}/issues/$PR_NUMBER"
            fi
          done

  label-devops-files:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Label devops file changes
        run: |
          for file in $(git diff --name-only ${{ github.event.before }} ${{ github.sha }}); do
            if [[ "$file" == .github/* || "$file" == .eb* ]]; then
              PR_NUMBER=$(jq --raw-output .number "$GITHUB_EVENT_PATH")
              curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                -H "Content-Type: application/json" \
                -X POST \
                -d '{"labels":["devops"]}' \
                "https://api.github.com/repos/${{ github.repository }}/issues/$PR_NUMBER"
            fi
          done
